fn main() {
    // The PDF renderer helper (M5-01) is generated by tools/pdf-helper/build.py and
    // bundled as a resource. An empty directory keeps Rust checks working on a
    // checkout without it; the app then reports the renderer as unavailable.
    std::fs::create_dir_all("../target/pdf-helper/runtime")
        .expect("create PDF helper resource directory");
    tauri_build::build();
}
