fn main() {
    if std::env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("linux") {
        // The explicit empty personal-wordlist API was added in Enchant 2.4.
        // Do not substitute the older API that reads the user's wordlists.
        pkg_config::Config::new()
            .atleast_version("2.4")
            .statik(false)
            .probe("enchant-2")
            .expect("Babel requires Enchant >=2.4 development files and its Hunspell provider; see docs/development.md");
    }
    // The PDF renderer helper (M5-01) is generated by tools/pdf-helper/build.py and
    // bundled as a resource. An empty directory keeps Rust checks working on a
    // checkout without it; the app then reports the renderer as unavailable.
    // Respect CARGO_TARGET_DIR so target-dir overrides (per-host or tmpfs builds)
    // still get the placeholder in the real output tree.
    let runtime_dir = std::env::var("CARGO_TARGET_DIR")
        .ok()
        .filter(|dir| std::path::Path::new(dir).is_absolute())
        .map(|dir| format!("{dir}/pdf-helper/runtime"))
        .unwrap_or_else(|| "../target/pdf-helper/runtime".to_owned());
    std::fs::create_dir_all(runtime_dir).expect("create PDF helper resource directory");
    tauri_build::build();
}
