fn main() {
    // The PDF renderer helper (M5-01) is generated by tools/pdf-helper/build.py and
    // bundled as a resource. An empty directory keeps Rust checks working on a
    // checkout without it; the app then reports the renderer as unavailable.
    // Respect CARGO_TARGET_DIR so target-dir overrides (per-host or tmpfs builds)
    // still get the placeholder in the real output tree.
    let runtime_dir = std::env::var("CARGO_TARGET_DIR")
        .ok()
        .filter(|dir| std::path::Path::new(dir).is_absolute())
        .map(|dir| format!("{dir}/pdf-helper/runtime"))
        .unwrap_or_else(|| "../target/pdf-helper/runtime".to_owned());
    std::fs::create_dir_all(runtime_dir).expect("create PDF helper resource directory");
    tauri_build::build();
}
