"""Build the third-party notice set for the Linux AppImage (M6-14, with M6-10).

Derives the bundled-library list from the built artifact itself
(target/release/bundle/appimage/babel.AppDir), maps every native library to
the Arch package that provided it, and retains the exact upstream licence
text for each entry under docs/third-party/package-licenses/. Generates the
machine-readable manifest (package-inventory.json), the human table
(package-libraries.md) and the in-package notice file (NOTICES.md).

Only ever run on the Arch build host: host package metadata comes from
pacman, and several licence texts are read from the installed packages.
The CI gate is tools/check-package-notices.py, which needs no host
packaging tools and only reads the committed manifest.

    python3 tools/build-package-notices.py [--appdir <dir>] [--check]

--check regenerates into a temporary directory and reports drift without
writing.

The generated Markdown/JSON is byte-deterministic but not prettier-stable;
finish with `pnpm prettier --write docs/third-party/NOTICES.md
docs/third-party/package-libraries.md docs/third-party/package-inventory.json`
and rebuild the package when NOTICES.md changed, so the in-package copy
stays byte-identical to the committed source.
"""

import hashlib
import json
import os
import re
import subprocess
import sys
import tempfile
import urllib.request
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
DOCS = REPO / "docs" / "third-party"
LICENSE_DIR = DOCS / "package-licenses"
DEFAULT_APPDIR = REPO / "target" / "release" / "bundle" / "appimage" / "babel.AppDir"

SPDX_DIR = Path("/usr/share/licenses/spdx")
SPDX_PACKAGE = "licenses"
SPDX_VERSION = "20240728-1"

# Fetched once by the authoring agent and pinned by SHA-256; the tool
# re-downloads and refuses anything else, so provenance stays verifiable.
UPSTREAM = [
    {
        "dest": "upstream-enchant-2.8.21-COPYING.LIB",
        "url": "https://raw.githubusercontent.com/AbiWord/enchant/main/COPYING.LIB",
        "sha256": "dc626520dcd53a22f727af3ee42c770e56c97a64fe3adb063799d8ab032fe551",
        "note": "Upstream Enchant COPYING.LIB (LGPL-2.1 FSF text); "
        "byte-compared against hunspell COPYING.LESSER, differs by one blank line.",
    },
    {
        "dest": "upstream-hunspell-1.7.5-COPYING",
        "url": "https://raw.githubusercontent.com/hunspell/hunspell/master/COPYING",
        "sha256": "640d90f6ee401241ff62834d0d1b33f83049e99b8bfdfa04ed1b0a1635dde3e7",
        "note": "Upstream Hunspell COPYING (GPL-2.0 FSF text).",
    },
    {
        "dest": "upstream-hunspell-1.7.5-COPYING.LESSER",
        "url": "https://raw.githubusercontent.com/hunspell/hunspell/master/COPYING.LESSER",
        "sha256": "7c6699c75f87b52bdc542db26d6b1b92892577cda46e20eceb79e2790a1c291b",
        "note": "Upstream Hunspell COPYING.LESSER (LGPL-2.1 FSF text).",
    },
    {
        "dest": "upstream-hunspell-1.7.5-COPYING.MPL",
        "url": "https://raw.githubusercontent.com/hunspell/hunspell/master/COPYING.MPL",
        "sha256": "53692a2ed6c6a2c6ec9b32dd0b820dfae91e0a1fcdf625ca9ed0bdf8705fcc4f",
        "note": "Upstream Hunspell COPYING.MPL (MPL-1.1 text).",
    },
    {
        "dest": "upstream-hunspell-1.7.5-license.hunspell",
        "url": "https://raw.githubusercontent.com/hunspell/hunspell/master/license.hunspell",
        "sha256": "3f7ddd07c296edbfe0a47c7bcc82038ad347a2c4f672345b24f95c624db68513",
        "note": "Upstream Hunspell per-file licence header (MPL-1.1/GPL-2.0/LGPL-2.1).",
    },
    {
        "dest": "upstream-hunspell-1.7.5-license.myspell",
        "url": "https://raw.githubusercontent.com/hunspell/hunspell/master/license.myspell",
        "sha256": "dcda061adeed22b26f276c01ec374f930789ae0d684e5aa8f8be309dd680ff20",
        "note": "Upstream MySpell per-file licence header (MPL-1.1/GPL-2.0/LGPL-2.1).",
    },
    {
        "dest": "upstream-libtool-ltdl.h",
        "url": "https://raw.githubusercontent.com/autotools-mirror/libtool/master/libltdl/ltdl.h",
        "sha256": "9538ec0f181f3dca031420a3273417b4af1fe35a47f216d180995e6bbda042e3",
        "note": "Upstream libltdl header carrying the Libtool-exception paragraph; "
        "the installed libtool COPYING.LIB holds only the LGPL-2.1 text.",
    },
    {
        "dest": "upstream-linuxdeploy-LICENSE.txt",
        "url": "https://raw.githubusercontent.com/linuxdeploy/linuxdeploy/master/LICENSE.txt",
        "sha256": "1edb41ae7601854ae15d113c3700beebd0ea3ed05b85e3786a94a72bb9916091",
        "note": "linuxdeploy MIT licence covering the AppRun/AppRun.wrapped launcher "
        "and the apprun-hooks script (AppRun header says 'autogenerated by linuxdeploy').",
    },
]

# Canonical SPDX texts read from the installed `licenses` package for Arch
# binary packages that ship no licence file of their own. The provenance of
# each such entry says so explicitly; the upstream COPYING was not verified
# locally for those (limitation L1 in package-libraries.md).
CANONICAL = {
    "LGPL-2.1-or-later": "spdx-LGPL-2.1-or-later.txt",
    "LGPL-2.1-only": "spdx-LGPL-2.1-or-later.txt",
    "LGPL-2.0-or-later": "spdx-LGPL-2.0-or-later.txt",
    "LGPL-2.0-only": "spdx-LGPL-2.0-or-later.txt",
    "LGPL-3.0-or-later": "spdx-LGPL-3.0-or-later.txt",
    "LGPL-3.0-only": "spdx-LGPL-3.0-or-later.txt",
    "GPL-2.0-or-later": "spdx-GPL-2.0-or-later.txt",
    "GPL-2.0-only": "spdx-GPL-2.0-only.txt",
    "GPL-3.0-or-later": "spdx-GPL-3.0-or-later.txt",
    "GPL-3.0-only": "spdx-GPL-3.0-only.txt",
    "MPL-1.1": "spdx-MPL-1.1.txt",
    "MPL-2.0": "spdx-MPL-2.0.txt",
    "CC0-1.0": "spdx-CC0-1.0.txt",
    "Apache-2.0": "spdx-Apache-2.0.txt",
    "PSF-2.0": "spdx-PSF-2.0.txt",
    "GFDL-1.3-or-later": "spdx-GFDL-1.3-or-later.txt",
    "Linux-syscall-note": "spdx-exceptions-Linux-syscall-note.txt",
}
SPDX_FILES = {
    "spdx-LGPL-2.1-or-later.txt": "LGPL-2.1-or-later.txt",
    "spdx-LGPL-2.0-or-later.txt": "LGPL-2.0-or-later.txt",
    "spdx-LGPL-3.0-or-later.txt": "LGPL-3.0-or-later.txt",
    "spdx-GPL-2.0-or-later.txt": "GPL-2.0-or-later.txt",
    "spdx-GPL-2.0-only.txt": "GPL-2.0-only.txt",
    "spdx-GPL-3.0-or-later.txt": "GPL-3.0-or-later.txt",
    "spdx-GPL-3.0-only.txt": "GPL-3.0-only.txt",
    "spdx-MPL-1.1.txt": "MPL-1.1.txt",
    "spdx-MPL-2.0.txt": "MPL-2.0.txt",
    "spdx-CC0-1.0.txt": "CC0-1.0.txt",
    "spdx-Apache-2.0.txt": "Apache-2.0.txt",
    "spdx-PSF-2.0.txt": "PSF-2.0.txt",
    "spdx-GFDL-1.3-or-later.txt": "GFDL-1.3-or-later.txt",
    "spdx-exceptions-Linux-syscall-note.txt": "exceptions/Linux-syscall-note.txt",
}

# Per-package overrides. "texts" entries are (kind, source, dest) with kind
# local (installed /usr/share/licenses/<pkg>/ file), canon (CANONICAL key) or
# upstream (UPSTREAM dest). Packages without an override copy their whole
# installed licence directory, or resolve every declared ID through CANONICAL
# and fail loudly on anything unmapped.
PACKAGE_TEXTS = {
    "enchant": {"texts": [("upstream", "upstream-enchant-2.8.21-COPYING.LIB")]},
    "hunspell": {
        "texts": [
            ("upstream", "upstream-hunspell-1.7.5-COPYING"),
            ("upstream", "upstream-hunspell-1.7.5-COPYING.LESSER"),
            ("upstream", "upstream-hunspell-1.7.5-COPYING.MPL"),
            ("upstream", "upstream-hunspell-1.7.5-license.hunspell"),
            ("upstream", "upstream-hunspell-1.7.5-license.myspell"),
        ]
    },
    "libtool": {
        "texts": [("local", "/usr/share/libtool/COPYING.LIB"), ("upstream", "upstream-libtool-ltdl.h")],
        "note": "Arch declares LGPL-2.0-or-later WITH Libtool-exception but ships "
        "LGPL-2.1 FSF text as COPYING.LIB; the exception paragraph is retained from "
        "upstream libltdl/ltdl.h.",
    },
    "libidn2": {
        "texts": [("canon", "GPL-2.0-or-later"), ("canon", "LGPL-3.0-or-later")],
        "note": "Arch shorthand 'GPL2 LGPL3' resolved by the installed "
        "/usr/include/idn2.h header: GPL-2.0-or-later AND LGPL-3.0-or-later, "
        "or both in parallel.",
    },
    "dbus": {
        "texts": [("local", "AFL-2.1.txt"), ("local", "COPYING"), ("canon", "GPL-2.0-or-later")],
        "note": "COPYING is the chooser (AFL-2.1 or GPL-2.0+); GPL-2.0 text is canonical.",
    },
    "graphite": {
        "texts": [("local", "COPYING"), ("canon", "GPL-2.0-or-later"), ("canon", "MPL-2.0")],
        "note": "COPYING is the tri-licence chooser header; GPL-2.0 and MPL-2.0 "
        "texts are canonical.",
    },
    "hyphen": {
        "texts": [("local", "LICENSE"), ("canon", "GPL-2.0-or-later"),
                  ("canon", "LGPL-2.1-or-later"), ("canon", "MPL-1.1")],
        "note": "LICENSE is the tri-licence chooser; the three texts are canonical.",
    },
    "cairo": {
        "texts": [("canon", "LGPL-2.1-only"), ("canon", "MPL-1.1")],
    },
    "glycin": {
        "texts": [("canon", "MPL-2.0"), ("canon", "LGPL-2.1-or-later")],
    },
    "libatomic": {
        "texts": [("local", "RUNTIME.LIBRARY.EXCEPTION"), ("canon", "GPL-3.0-or-later"),
                  ("canon", "GFDL-1.3-or-later")],
        "note": "GFDL-1.3 covers GCC manuals, not the bundled library; retained for "
        "completeness against the declared licence set.",
    },
    "libtasn1": {
        "texts": [("local", "COPYING"), ("canon", "LGPL-2.1-or-later"),
                  ("canon", "GFDL-1.3-or-later")],
        "note": "Installed COPYING holds the GPL-3.0 text; LGPL-2.1 is canonical and "
        "GFDL-1.3 covers the manual, retained for completeness.",
    },
    "systemd-libs": {
        "texts": [("canon", "LGPL-2.1-or-later"), ("canon", "CC0-1.0"),
                  ("canon", "GPL-2.0-or-later"), ("canon", "Linux-syscall-note")],
    },
    "util-linux-libs": {
        "texts": [("local", "COPYING.BSD-2-Clause"), ("local", "COPYING.BSD-3-Clause"),
                  ("local", "COPYING.BSD-4-Clause-UC"), ("local", "COPYING.ISC"),
                  ("local", "util-linux-BSD-2-Clause.txt"),
                  ("canon", "GPL-2.0-only"), ("canon", "GPL-2.0-or-later"),
                  ("canon", "GPL-3.0-or-later"), ("canon", "LGPL-2.1-or-later")],
        "note": "Whole declared set retained; libmount/libblkid/libuuid fall under "
        "the BSD-family texts per util-linux documentation and pins.json (libuuid).",
    },
    "libgcrypt": {
        "texts": [("local", "COPYING.LIB"), ("local", "LICENSES"),
                  ("canon", "GPL-2.0-only"), ("canon", "GPL-2.0-or-later"),
                  ("canon", "LGPL-2.0-or-later")],
        "note": "COPYING.LIB is LGPL-2.1; LICENSES aggregates the remaining file "
        "notices; GPL/LGPL-2.0 wordings are canonical.",
    },
    "zstd": {
        "texts": [("local", "LICENSE"), ("canon", "GPL-2.0-only")],
        "note": "LICENSE holds the BSD-3-Clause text; the GPL-2.0-only wording for "
        "the dual-licensed files is canonical.",
    },
    "xz": {
        "texts": [("local", "COPYING"), ("local", "COPYING.0BSD"),
                  ("canon", "GPL-2.0-or-later"), ("canon", "LGPL-2.1-or-later")],
        "note": "COPYING is the XZ Utils licensing overview; 0BSD text is the "
        "installed COPYING.0BSD.",
    },
    "libcups": {
        "texts": [("local", "LICENSE"), ("local", "NOTICE"),
                  ("canon", "Apache-2.0")],
        "note": "LICENSE/NOTICE are the CUPS Apache-2.0-with-exceptions bundle.",
    },
    "hidapi": {
        "texts": [("local", "LICENSE.txt"), ("local", "LICENSE-bsd.txt"),
                  ("local", "LICENSE-gpl3.txt"), ("local", "LICENSE-orig.txt")],
    },
    "webkit2gtk-4.1": {"texts": [("local", "LICENSE")]},
    "webkitgtk-6.0": {
        "texts": [("local", "LICENSE")],
        "note": "Typelib data files only; LICENSE is byte-identical to the "
        "webkit2gtk-4.1 aggregate.",
    },
}


def run(*args):
    return subprocess.check_output(list(args), text=True).strip()


def sha256(path):
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for chunk in iter(lambda: handle.read(65536), b""):
            digest.update(chunk)
    return digest.hexdigest()


def fetch(url, expected):
    request = urllib.request.Request(url, headers={"User-Agent": "babel-notices-tool"})
    with urllib.request.urlopen(request, timeout=60) as response:
        data = response.read()
    actual = hashlib.sha256(data).hexdigest()
    if actual != expected:
        raise SystemExit(f"Upstream fetch mismatch for {url}:\nexpected {expected}\nactual   {actual}")
    return data


def package_info(package):
    out = run("pacman", "-Qi", package)
    info = {}
    for line in out.splitlines():
        if line.startswith("Version"):
            info["version"] = line.split(":", 1)[1].strip()
        elif line.startswith("Licenses"):
            info["declared"] = line.split(":", 1)[1].strip()
        elif line.startswith("URL"):
            info["upstream"] = line.split(":", 1)[1].strip()
    return info


def find_host(basename):
    direct = Path("/usr/lib") / basename
    if direct.exists():
        return direct
    found = run("find", "/usr/lib", "-name", basename).split()
    return Path(found[0]) if found else None


def owner_of(path):
    out = run("pacman", "-Qo", str(path))
    # "... is owned by <pkg> <ver>"
    return out.rsplit("owned by", 1)[1].strip().split()[0]


def cargo_dir(crate):
    matches = sorted(Path.home().glob(f".cargo/registry/src/*/{crate}"))
    if not matches:
        raise SystemExit(f"Cargo registry source for {crate} not found")
    return matches[0]


def add_special_sections(entries, packages, appdir, out_licenses, written, place,
                         check_only):
    # Statically linked libgit2 inside usr/bin/babel-desktop (ADR 0011).
    sys_libgit2 = cargo_dir("libgit2-sys-0.18.8+1.9.7")
    git2 = cargo_dir("git2-0.21.0")
    (out_licenses / "libgit2-1.9.7-COPYING").write_bytes(
        (sys_libgit2 / "libgit2" / "COPYING").read_bytes())
    written["libgit2-1.9.7-COPYING"] = {
        "source": "vendored libgit2 source compiled into the binary "
                  f"({sys_libgit2}/libgit2/COPYING); byte-identical to the installed "
                  f"libgit2 {run('pacman', '-Q', 'libgit2')} package COPYING",
        "sha256": sha256(out_licenses / "libgit2-1.9.7-COPYING")}
    (out_licenses / "libgit2-sys-0.18.8-LICENSE-MIT").write_bytes(
        (sys_libgit2 / "LICENSE-MIT").read_bytes())
    written["libgit2-sys-0.18.8-LICENSE-MIT"] = {
        "source": f"Rust binding licence ({sys_libgit2}/LICENSE-MIT); the git2 crate "
                  "LICENSE-MIT is byte-identical",
        "sha256": sha256(out_licenses / "libgit2-sys-0.18.8-LICENSE-MIT")}
    (out_licenses / "git2-0.21.0-LICENSE-APACHE").write_bytes(
        (git2 / "LICENSE-APACHE").read_bytes())
    written["git2-0.21.0-LICENSE-APACHE"] = {
        "source": f"Rust binding licence ({git2}/LICENSE-APACHE)",
        "sha256": sha256(out_licenses / "git2-0.21.0-LICENSE-APACHE")}
    binary = "usr/bin/babel-desktop"
    entries.append({
        "package": "babel-desktop (statically linked libgit2)",
        "kind": "static-link",
        "version": "libgit2 1.9.7 via libgit2-sys 0.18.8 / git2 0.21.0 (Cargo.lock)",
        "declared": "GPL-2.0 with linking exception (libgit2 C); "
                    "MIT OR Apache-2.0 (git2 Rust bindings)",
        "upstream": "https://github.com/libgit2/libgit2",
        "note": "ldd shows no libgit2: the vendored build links it statically "
                "(cargo:rustc-link-lib=static=git2). HTTPS/SSH features are off, so no "
                "static OpenSSL/libssh2 payload. Transitive Rust-crate texts: L2.",
        "texts": [
            {"file": "libgit2-1.9.7-COPYING",
             "source": written["libgit2-1.9.7-COPYING"]["source"],
             "sha256": written["libgit2-1.9.7-COPYING"]["sha256"]},
            {"file": "libgit2-sys-0.18.8-LICENSE-MIT",
             "source": written["libgit2-sys-0.18.8-LICENSE-MIT"]["source"],
             "sha256": written["libgit2-sys-0.18.8-LICENSE-MIT"]["sha256"]},
            {"file": "git2-0.21.0-LICENSE-APACHE",
             "source": written["git2-0.21.0-LICENSE-APACHE"]["source"],
             "sha256": written["git2-0.21.0-LICENSE-APACHE"]["sha256"]},
        ],
        "stems": ["babel-desktop"],
        "bundled": [{"path": binary, "sha256": sha256(appdir / binary),
                     "bytes": (appdir / binary).stat().st_size}],
    })

    # linuxdeploy launcher (AppRun script says autogenerated by linuxdeploy).
    entries.append({
        "package": "linuxdeploy (AppImage launcher)",
        "kind": "launcher",
        "version": "launcher generated at build time",
        "declared": "MIT",
        "upstream": "https://github.com/linuxdeploy/linuxdeploy",
        "note": "",
        "texts": [{"file": "upstream-linuxdeploy-LICENSE.txt",
                   "source": written["upstream-linuxdeploy-LICENSE.txt"]["source"],
                   "sha256": written["upstream-linuxdeploy-LICENSE.txt"]["sha256"]}],
        "stems": ["AppRun", "AppRun.wrapped", "linuxdeploy-plugin-gtk.sh"],
        "bundled": [
            {"path": rel, "sha256": sha256(appdir / rel),
             "bytes": (appdir / rel).stat().st_size}
            for rel in sorted(packages.get("linuxdeploy", {}).get("bundled", []))
        ],
    })

    add_pdf_helper(entries, appdir, out_licenses, written, place)
    add_js_runtime(entries, out_licenses, written, place)

    # Host prerequisites: linked but not bundled (plus non-library needs).
    host_libs = host_prerequisites(appdir)
    entries.append({
        "package": "host prerequisites (NOT bundled, NOT redistributed)",
        "kind": "host",
        "version": "",
        "declared": "",
        "upstream": "",
        "note": "Loaded from the host at runtime or required around the package; "
                "no notice text is retained because nothing is redistributed.",
        "texts": [],
        "stems": [],
        "bundled": [],
        "host": host_libs + [
            {"name": "hunspell dictionaries (<datadir>/hunspell, e.g. /usr/share/hunspell)",
             "note": "Host prerequisite per ADR 0045; the packaged provider reads them, "
                     "writing and Save work without them."},
            {"name": "libfuse2 + FUSE kernel support",
             "note": "Mounts the AppImage on launch; provided by the host."},
        ],
    })


def host_prerequisites(appdir):
    libs = Path(appdir) / "usr" / "lib"
    env = {"LD_LIBRARY_PATH": str(libs), "PATH": "/usr/bin:/bin"}
    found = {}
    targets = [appdir / "usr/bin/babel-desktop",
               libs / "webkit2gtk-4.1" / "WebKitWebProcess",
               libs / "webkit2gtk-4.1" / "WebKitNetworkProcess"]
    for target in targets:
        if not target.is_file():
            continue
        out = subprocess.run(["ldd", str(target)], capture_output=True, text=True,
                             env={**os.environ, **env}).stdout
        for line in out.splitlines():
            if "=>" not in line:
                continue
            name, _, rest = line.strip().partition("=>")
            path = rest.strip().split()[0]
            if path.startswith(str(appdir)) or path.startswith(str(libs)):
                continue
            found.setdefault(name.strip(), {"resolved": path, "neededBy": []})
            found[name.strip()]["neededBy"].append(target.name)
    return [{"name": name, "resolved": info["resolved"],
             "neededBy": sorted(set(info["neededBy"])),
             "note": "Loaded from the host; not bundled, not redistributed."}
            for name, info in sorted(found.items())]


def add_pdf_helper(entries, appdir, out_licenses, written, place):
    runtime = REPO / "target" / "pdf-helper" / "runtime"
    pins = json.loads((REPO / "tools" / "pdf-helper" / "pins.json").read_text())
    build = json.loads((runtime / "BUILD.json").read_text())
    helper = runtime.relative_to(REPO).as_posix()
    tree = appdir / "usr/lib/babel/pdf-helper"

    for name, dest in [
            ("CPython-LICENSE.txt", "cpython-3.13.16-LICENSE.txt"),
            ("CourierPrime-OFL.txt", "courier-prime-OFL-1.1.txt"),
            ("screenplain-licenses-LICENSE.txt", "screenplain-0.12.0-LICENSE.txt"),
            ("reportlab-licenses-LICENSE", "reportlab-4.4.7-LICENSE"),
            ("charset_normalizer-licenses-LICENSE", "charset-normalizer-3.5.1-LICENSE")]:
        place(dest, (runtime / "licenses" / name).read_bytes(),
              f"pinned pdf-helper runtime ({helper}/licenses/{name}; "
              "assembled by tools/pdf-helper/build.py from the pinned inputs below)")

    font_dir = tree / "app/lib/reportlab/fonts"
    for name in ("bitstream-vera-license.txt", "DarkGarden-copying.txt",
                 "DarkGarden-copying-gpl.txt"):
        dest = f"reportlab-{name}"
        place(dest, (font_dir / name).read_bytes(),
              "shipped inside the pinned reportlab wheel "
              f"({helper}/app/lib/reportlab/fonts/{name})")

    python = pins["python"]
    entries.append({
        "package": "python-build-standalone CPython (bundled interpreter)",
        "kind": "interpreter",
        "version": python["file"],
        "declared": python["license"],
        "upstream": python["url"],
        "note": f"SHA-256 {python['sha256']}. Whole runtime tree "
                f"usr/lib/babel/pdf-helper ({build['files']} files, "
                f"tree {build['treeSha256']}) is attributed here; per-file hashes live in "
                f"the shipped {helper}/BUILD.json. Statically linked components follow "
                "as separate entries.",
        "texts": [{"file": "cpython-3.13.16-LICENSE.txt",
                   "source": written["cpython-3.13.16-LICENSE.txt"]["source"],
                   "sha256": written["cpython-3.13.16-LICENSE.txt"]["sha256"]}],
        "stems": ["python3.13", "libpython3.13"],
        "bundled": [{"path": "usr/lib/babel/pdf-helper/**",
                     "treeSha256": build["treeSha256"], "files": build["files"],
                     "bytes": build["bytes"],
                     "pinsSha256": sha256(REPO / "tools/pdf-helper/pins.json")}],
    })

    static_sources = {
        "OpenSSL 3.5.9": "/usr/share/licenses/openssl/LICENSE.txt",
        "libedit (readline backend: editline)": "/usr/share/licenses/libedit/COPYING",
        "ncurses 6.5": "/usr/share/licenses/ncurses/COPYING",
        "SQLite 3.53.1": "/usr/share/licenses/sqlite/license.txt",
        "expat 2.8.5": "/usr/share/licenses/expat/COPYING",
        "mpdecimal 4.0.0": "/usr/share/licenses/mpdecimal/COPYRIGHT.txt",
        "zlib 1.3.2": "/usr/share/licenses/zlib/LICENSE",
        "bzip2": "/usr/share/licenses/bzip2/LICENSE",
        "xz/liblzma": "/usr/share/licenses/xz/COPYING.0BSD",
        "libffi": "/usr/share/licenses/libffi/LICENSE",
        "libuuid (util-linux)": "/usr/share/licenses/util-linux-libs/COPYING.BSD-3-Clause",
    }
    interpreter_bin = tree / "python/bin/python3.13"
    bin_record = {"path": "usr/lib/babel/pdf-helper/python/bin/python3.13",
                  "sha256": sha256(interpreter_bin),
                  "bytes": interpreter_bin.stat().st_size}
    for component, expected in pins["python"]["staticComponents"].items():
        if component == "comment":
            continue
        src = Path(static_sources[component])
        dest = f"cpython-static-{src.parent.name}-{src.name}"
        place(dest, src.read_bytes(),
              f"installed {src.parent.name} package (/{src.as_posix().lstrip('/')}); "
              f"licence claim {expected!r} per tools/pdf-helper/pins.json; component "
              "provenance is the python-build-standalone release above")
        entries.append({
            "package": f"CPython static component: {component}",
            "kind": "static-link",
            "version": f"{component} (per tools/pdf-helper/pins.json)",
            "declared": expected,
            "upstream": python["url"],
            "note": "Statically linked into the bundled python3.13 binary; the shipped "
                    "file is that binary (hash below). Component upstream URLs are not "
                    "independently verified beyond the python-build-standalone release.",
            "texts": [{"file": dest, "source": written[dest]["source"],
                       "sha256": written[dest]["sha256"]}],
            "stems": [],
            "bundled": [bin_record],
        })

    for wheel in pins["wheels"]:
        name = wheel["name"]
        dest = {"screenplain": "screenplain-0.12.0-LICENSE.txt",
                "reportlab": "reportlab-4.4.7-LICENSE",
                "charset-normalizer": "charset-normalizer-3.5.1-LICENSE"}[name]
        entries.append({
            "package": f"Python wheel: {name} {wheel['version']}",
            "kind": "wheel",
            "version": f"{wheel['file']} (SHA-256 {wheel['sha256']})",
            "declared": wheel["license"],
            "upstream": wheel["url"],
            "note": "Extracted into usr/lib/babel/pdf-helper/app/lib/. Pillow is a "
                    "refusing stub, not the wheel (pins.json).",
            "texts": [{"file": dest, "source": written[dest]["source"],
                       "sha256": written[dest]["sha256"]}],
            "stems": [],
            "bundled": [{"path": f"usr/lib/babel/pdf-helper/app/lib/{name}*",
                         "wheelSha256": wheel["sha256"]}],
        })

    fonts = [(p.relative_to(tree).as_posix(), sha256(p), p.stat().st_size)
             for p in sorted(tree.rglob("*"))
             if p.is_file() and p.suffix.lower() in
             (".ttf", ".otf", ".pfb", ".afm", ".sfd")]
    courier = [f for f in fonts if "courier_prime" in f[0].lower()]
    vera = [f for f in fonts if "vera" in f[0].lower() or "hb-test" in f[0].lower()]
    darkgarden = [f for f in fonts if "darkgarden" in f[0].lower()]
    base14 = [f for f in fonts if f not in courier + vera + darkgarden]
    for title, members, text_files, declared, upstream, note in [
        ("Courier Prime (embedded renderer fonts)", courier,
         ["courier-prime-OFL-1.1.txt"], "OFL-1.1",
         "as bundled in the screenplain 0.12.0 wheel (URL above)",
         "SHA-256 verified against tools/pdf-helper/pins.json fonts section."),
        ("Bitstream Vera + HarfBuzz test font (reportlab data)", vera,
         ["reportlab-bitstream-vera-license.txt"], "Bitstream Vera licence",
         "shipped inside the pinned reportlab wheel",
         "hb-test.ttf is ReportLab's bundled test font, covered by the wheel licence."),
        ("DarkGarden (reportlab Type 1 data)", darkgarden,
         ["reportlab-DarkGarden-copying.txt", "reportlab-DarkGarden-copying-gpl.txt",
          "spdx-GPL-2.0-or-later.txt"], "GPL-2.0-or-later",
         "shipped inside the pinned reportlab wheel",
         "GPL-2.0 wording is the canonical SPDX text."),
        ("PDF base-14 metrics (reportlab data)", base14, ["reportlab-4.4.7-LICENSE"],
         "BSD-3-Clause (wheel licence)",
         "shipped inside the pinned reportlab wheel",
         "No separate notice ships in the wheel for these metrics files."),
    ]:
        entries.append({
            "package": f"Font data: {title}",
            "kind": "font",
            "version": "pinned wheel contents (see wheel entries)",
            "declared": declared,
            "upstream": upstream,
            "note": note,
            "texts": [{"file": dest, "source": written[dest]["source"],
                       "sha256": written[dest]["sha256"]} for dest in text_files],
            "stems": [Path(path).name for path, _, _ in members],
            "bundled": [{"path": f"usr/lib/babel/pdf-helper/{path}", "sha256": digest,
                         "bytes": size} for path, digest, size in members],
        })


def add_js_runtime(entries, out_licenses, written, place):
    direct = {
        "react": ("MIT", "https://github.com/facebook/react"),
        "react-dom": ("MIT", "https://github.com/facebook/react"),
        "@tauri-apps/api": ("Apache-2.0 OR MIT", "https://github.com/tauri-apps/tauri"),
    }
    for name, (spdx, upstream) in direct.items():
        meta = json.loads((REPO / "node_modules" / name / "package.json").read_text())
        files = sorted((REPO / "node_modules" / name).glob("LICENSE*"))
        texts = []
        for src in files:
            if src.suffix == ".spdx":
                continue
            dest = f"{name.replace('/', '-')}-{meta['version']}-{src.name}"
            place(dest, src.read_bytes(),
                  f"installed {name} {meta['version']} (node_modules/{name}/{src.name})")
            texts.append({"file": dest, "source": written[dest]["source"],
                          "sha256": written[dest]["sha256"]})
        entries.append({
            "package": f"npm runtime: {name}",
            "kind": "js",
            "version": f"{meta['version']} (declared {spdx}; integrity pinned in pnpm-lock.yaml)",
            "declared": spdx,
            "upstream": upstream,
            "note": "Bundled into the frontend dist embedded in usr/bin/babel-desktop. "
                    "Transitive npm module texts: L3.",
            "texts": texts,
            "stems": [],
            "bundled": [{"path": "frontend dist embedded in usr/bin/babel-desktop"}],
        })
    entries.append({
        "package": "npm runtime: pdfjs-dist + ProseMirror set (already recorded)",
        "kind": "js",
        "version": "pdfjs-dist 6.3.289; prosemirror-model 1.25.12, -state 1.4.4, "
                   "-history 1.5.0, -view 1.42.6, -transform 1.12.2, "
                   "orderedmap 2.1.1, rope-sequence 1.3.4",
        "declared": "Apache-2.0 (pdfjs-dist); MIT (ProseMirror set)",
        "upstream": "https://github.com/mozilla/pdfjs-dist",
        "note": "Exact texts retained under docs/third-party/pdf-viewer/ and "
                "docs/third-party/editor-licenses/; referenced here, not duplicated.",
        "texts": [],
        "stems": [],
        "bundled": [{"path": "frontend dist embedded in usr/bin/babel-desktop"}],
        "refs": ["pdf-viewer/pdfjs-dist-6.3.289-LICENSE.txt",
                 "editor-licenses/prosemirror-model-1.25.12.txt",
                 "editor-licenses/prosemirror-state-1.4.4.txt",
                 "editor-licenses/prosemirror-history-1.5.0.txt",
                 "editor-licenses/prosemirror-view-1.42.6.txt",
                 "editor-licenses/prosemirror-transform-1.12.2.txt",
                 "editor-licenses/orderedmap-2.1.1.txt",
                 "editor-licenses/rope-sequence-1.3.4.txt"],
    })


def text_links(entry):
    links = [f"[{t['file']}](package-licenses/{t['file']})" for t in entry["texts"]]
    links += [f"[{r}]({r})" for r in entry.get("refs", [])]
    return "<br>".join(links) if links else "—"


def render_libraries_md(inventory):
    lines = []
    add = lines.append
    artifact = inventory["artifact"]
    add("# Bundled third-party libraries (AppImage)")
    add("")
    add("M6-14 notices, with M6-10. The library list is derived from the built "
        "artifact itself: `babel_0.0.1_amd64.AppImage` extracted with "
        "`--appimage-extract`, every ELF binary, provider module and font inventoried, "
        "each mapped to the Arch package that provided it. The machine-readable "
        "record is [package-inventory.json](package-inventory.json); the file the "
        "package ships is [NOTICES.md](NOTICES.md) "
        "(`usr/lib/babel/THIRD-PARTY-NOTICES.md` in the package).")
    add("")
    add(f"Inventoried artifact AppImage SHA-256: `{artifact['appimageSha256']}`.")
    add("")
    add("Scope: " + inventory["scope"])
    add("")
    add("## Limitations")
    add("")
    for limitation in inventory["limitations"]:
        add(f"- {limitation}")
    add("")
    add("Dictionaries (SCOWL/`hunspell-en_us`) stay a host prerequisite per "
        "[ADR 0045](../decisions/0045-user-install-and-packaged-spelling.md): "
        "bundling one language would add dictionary licence texts for partial "
        "coverage while every other language still came from the host. This task "
        "builds the notice file and the CI gate, so bundling a dictionary later is "
        "mechanically unblocked; the decision is recorded in "
        "[ADR 0046](../decisions/0046-package-notice-file.md).")
    add("")
    add("## Native closure (dynamically linked, bundled by linuxdeploy)")
    add("")
    add("Each row is one Arch package that provided bundled files. Version, declared "
        "licence and upstream URL are the installed-package metadata as resolved on "
        "the build host; per-file SHA-256 is in `package-inventory.json`. `-only` and "
        "`-or-later` variants share one licence document; the difference lives in the "
        "project's copyright notice, not the text.")
    add("")
    add("| Package | Version | Declared licence | Exact notice text(s) | Bundled files |")
    add("| ------- | ------- | ---------------- | -------------------- | ------------- |")
    for entry in inventory["entries"]:
        if entry["kind"] != "native":
            continue
        files = len(entry["bundled"])
        note = f" {entry['note']}" if entry["note"] else ""
        add(f"| {entry['package']} | {entry['version']} | {entry['declared']} | "
            f"{text_links(entry)} | {files}{note} |")
    add("")
    add("### Spellcheck provider (ADR 0045)")
    add("")
    add("The `enchant` row covers `usr/lib/libenchant-2.so.2` and the staged "
        "`usr/lib/enchant-2/enchant_hunspell.so` provider; the `hunspell` row covers "
        "`usr/lib/libhunspell-1.7.so.0`. Dictionaries are not bundled (host "
        "prerequisite above).")
    add("")
    for title, kind in [("Statically linked code", "static-link"),
                        ("Bundled interpreter and Python packages", "interpreter"),
                        ("Python wheels", "wheel"),
                        ("Fonts", "font"),
                        ("JavaScript runtime", "js"),
                        ("AppImage launcher", "launcher")]:
        members = [e for e in inventory["entries"] if e["kind"] == kind]
        if kind == "interpreter":
            members += [e for e in inventory["entries"]
                        if e["kind"] in ("wheel",)]
        if kind == "wheel":
            continue
        if not members:
            continue
        add(f"## {title}")
        add("")
        for entry in members:
            bundled = entry["bundled"]
            if len(bundled) == 1 and "treeSha256" in bundled[0]:
                files = (f"tree {bundled[0]['path']} "
                         f"({bundled[0]['files']} files, tree {bundled[0]['treeSha256']})")
            else:
                files = ", ".join(f"`{b['path']}`" for b in bundled)
            add(f"### {entry['package']}")
            add("")
            add(f"- Version: {entry['version']}")
            add(f"- Licence: {entry['declared']}")
            if entry["upstream"]:
                add(f"- Upstream: {entry['upstream']}")
            if entry["note"]:
                add(f"- Note: {entry['note']}")
            add(f"- Notice text(s): {text_links(entry)}")
            add(f"- Shipped as: {files}")
            add("")
    host = next(e for e in inventory["entries"] if e["kind"] == "host")
    add("## Host prerequisites versus redistribution obligations")
    add("")
    add("Everything above is redistributed inside the AppImage and therefore carries "
        "a retained notice. The following is loaded from the host at runtime or "
        "required around the package; it is a declared host prerequisite, not a "
        "redistribution obligation:")
    add("")
    for item in host["host"]:
        if "resolved" in item:
            add(f"- `{item['name']}` resolves to `{item['resolved']}` "
                f"(needed by {', '.join(item['neededBy'])}). {item['note']}")
        else:
            add(f"- {item['name']}: {item['note']}")
    add("")
    (DOCS / "package-libraries.md").write_text("\n".join(lines))


def render_notices_md(inventory, out_licenses):
    lines = []
    add = lines.append
    link_escape = re.compile(r"\[([^\]]+)\]\((?![a-zA-Z][a-zA-Z0-9+.-]*:|#|/)")
    version = json.loads((REPO / "src-tauri" / "tauri.conf.json").read_text())["version"]
    add("# babel third-party notices")
    add("")
    add("This file ships inside the Linux package at "
        "`usr/lib/babel/THIRD-PARTY-NOTICES.md` and is readable in the app through "
        "Tools \u2192 Third-party notices. It is generated by "
        "`tools/build-package-notices.py` from `docs/third-party/package-inventory.json`; "
        "do not edit by hand.")
    add("")
    add(f"Notices for babel {version}. The exact inventoried artifact hash lives in "
        "`docs/third-party/package-inventory.json` alongside this file's source; "
        "a notice file cannot name the hash of the container that carries it.")
    add("")
    add("Each entry names the exact version as resolved, the SPDX licence id, the "
        "upstream source and the SHA-256 of the exact file shipped. The verbatim "
        "upstream licence text follows each entry. `-only` and `-or-later` variants "
        "share one licence document.")
    add("")
    for entry in inventory["entries"]:
        if entry["kind"] == "host":
            continue
        add(f"## {entry['package']}")
        add("")
        if entry["version"]:
            add(f"- Version: {entry['version']}")
        add(f"- Licence: {entry['declared'] or entry['kind']}")
        if entry["upstream"]:
            add(f"- Upstream: {entry['upstream']}")
        if entry["note"]:
            add(f"- Note: {entry['note']}")
        for item in entry["bundled"]:
            if "sha256" in item:
                add(f"- Shipped: `{item['path']}` "
                    f"(SHA-256 `{item['sha256']}`, {item.get('bytes', '?')} bytes)")
            elif "treeSha256" in item:
                add(f"- Shipped: `{item['path']}` "
                    f"({item['files']} files, tree SHA-256 `{item['treeSha256']}`, "
                    f"pins SHA-256 `{item['pinsSha256']}`)")
            elif "wheelSha256" in item:
                add(f"- Shipped: `{item['path']}` "
                    f"(wheel SHA-256 `{item['wheelSha256']}`)")
            else:
                add(f"- Shipped: `{item['path']}`")
        for ref in entry.get("refs", []):
            add(f"- Retained notice (see repo docs/third-party/{ref})")
        for text in entry["texts"]:
            data = (out_licenses / text["file"]).read_text(encoding="utf-8",
                                                           errors="replace")
            assert "```" not in data, text["file"]
            # Embedded upstream texts may contain relative links that are only
            # meaningful in their own repository. Replace the opening bracket
            # with an entity so the notice renders the literal text instead of
            # a broken link; the retained record under package-licenses/ stays
            # byte-exact.
            data = link_escape.sub(r"&#91;\1](", data)
            add(f"- Provenance of `{text['file']}`: {text['source']}")
            add("")
            add("```")
            add(data.rstrip("\n"))
            add("```")
        add("")
    (DOCS / "NOTICES.md").write_text("\n".join(lines) + "\n")


def main():
    appdir = DEFAULT_APPDIR
    check_only = False
    args = sys.argv[1:]
    if "--check" in args:
        check_only = True
        args.remove("--check")
    if args:
        appdir = Path(args[0])
    appdir = appdir.resolve(strict=True)

    if check_only:
        out_licenses = Path(tempfile.mkdtemp(prefix="babel-notices-")) / "package-licenses"
    else:
        out_licenses = LICENSE_DIR
    out_licenses.mkdir(parents=True, exist_ok=True)
    written = {}  # dest -> {source, sha256}

    def place(dest, data, source):
        (out_licenses / dest).write_bytes(data)
        written[dest] = {"source": source, "sha256": hashlib.sha256(data).hexdigest()}

    for item in UPSTREAM:
        place(item["dest"], fetch(item["url"], item["sha256"]),
              f"upstream {item['url']} (SHA-256 pinned in tools/build-package-notices.py)")

    for dest, spdx_file in SPDX_FILES.items():
        src = SPDX_DIR / spdx_file
        place(dest, src.read_bytes(),
              f"canonical SPDX text from installed {SPDX_PACKAGE} {SPDX_VERSION} "
              f"(/usr/share/licenses/spdx/{spdx_file})")

    # Walk the artifact.
    elf_files, font_files, data_files, own_files = [], [], [], []
    for path in sorted(appdir.rglob("*")):
        if path.is_symlink() or not path.is_file():
            continue
        rel = path.relative_to(appdir).as_posix()
        if (appdir / "usr/lib/babel/pdf-helper").as_posix() in path.as_posix():
            continue
        with open(path, "rb") as handle:
            magic = handle.read(4)
        if magic == b"\x7fELF":
            elf_files.append(rel)
        elif path.suffix.lower() in (".ttf", ".otf", ".woff", ".woff2"):
            font_files.append(rel)
        else:
            data_files.append(rel)

    def resolve_package(basename):
        host = find_host(basename)
        if host is None:
            raise SystemExit(f"No host file for bundled {basename}; cannot attribute provenance")
        return owner_of(host), host

    KNOWN_BINARIES = {
        # Generated at packaging time; no host counterpart exists.
        "AppRun": "linuxdeploy",
        "AppRun.wrapped": "linuxdeploy",
        "usr/bin/babel-desktop": "babel-desktop",
    }

    packages = {}
    for rel in elf_files:
        if rel in KNOWN_BINARIES:
            packages.setdefault(KNOWN_BINARIES[rel], {"bundled": []})["bundled"].append(rel)
            continue
        basename = Path(rel).name
        package, _ = resolve_package(basename)
        packages.setdefault(package, {"bundled": []})["bundled"].append(rel)
    # GSettings schemas and other bundled data attribute to their owners too.
    for rel in data_files:
        if rel.startswith("usr/share/glib-2.0/schemas/"):
            host = Path("/usr/share/glib-2.0/schemas") / Path(rel).name
            if Path(rel).name == "gschemas.compiled":
                # Generated at build time by glib-compile-schemas from the data above.
                packages.setdefault("glib2", {"bundled": []})["bundled"].append(rel)
            elif host.exists():
                packages.setdefault(owner_of(host), {"bundled": []})["bundled"].append(rel)
        elif rel in KNOWN_BINARIES:
            packages.setdefault(KNOWN_BINARIES[rel], {"bundled": []})["bundled"].append(rel)
        elif rel.startswith("apprun-hooks/"):
            packages.setdefault("linuxdeploy", {"bundled": []})["bundled"].append(rel)

    entries = []
    for package in sorted(packages):
        if package in ("linuxdeploy", "babel-desktop"):
            continue
        info = package_info(package)
        override = PACKAGE_TEXTS.get(package, {})
        texts = []
        if "texts" in override:
            for kind, ref in override["texts"]:
                if kind == "local":
                    src = Path(ref) if ref.startswith("/") else Path("/usr/share/licenses") / package / ref
                    dest = f"{package}-{info['version']}-{src.name}"
                    place(dest, src.read_bytes(),
                          f"installed {package} {info['version']} (/{src.as_posix().lstrip('/')})")
                elif kind == "canon":
                    dest = CANONICAL[ref]
                elif kind == "upstream":
                    dest = ref
                else:
                    raise SystemExit(f"Unknown text kind {kind!r} for {package}")
                texts.append({"file": dest, "source": written[dest]["source"],
                              "sha256": written[dest]["sha256"]})
        else:
            lic_dir = Path("/usr/share/licenses") / package
            if lic_dir.is_dir():
                for item in sorted(lic_dir.rglob("*")):
                    if item.is_file():
                        dest = f"{package}-{info['version']}-{item.relative_to(lic_dir).as_posix().replace('/', '-')}"
                        place(dest, item.read_bytes(),
                              f"installed {package} {info['version']} (/{item.relative_to('/')})")
                        texts.append({"file": dest, "source": written[dest]["source"],
                                      "sha256": written[dest]["sha256"]})
            else:
                normalized = info["declared"].replace(" WITH ", " OR ").replace(" AND ", " OR ")
                tokens = [t.strip() for chunk in normalized.split(" OR ")
                          for t in chunk.split("  ") if t.strip()]
                for token in tokens:
                    if not token or token in ("custom",):
                        continue
                    if token not in CANONICAL:
                        raise SystemExit(
                            f"{package} declares {token!r} with no canonical mapping and no "
                            f"installed licence dir; add a PACKAGE_TEXTS override")
                # Record in declared order, deduplicated.
                seen = set()
                for token in info["declared"].split():
                    token = token.strip()
                    if token in CANONICAL and CANONICAL[token] not in seen:
                        seen.add(CANONICAL[token])
                        dest = CANONICAL[token]
                        texts.append({"file": dest, "source": written[dest]["source"],
                                      "sha256": written[dest]["sha256"]})
                override = {"note": "Arch binary package ships no licence file; canonical "
                            "SPDX text(s) retained (limitation L1)."}
        entries.append({
            "package": package,
            "kind": "native",
            "version": info["version"],
            "declared": info["declared"],
            "upstream": info.get("upstream", ""),
            "note": override.get("note", ""),
            "texts": texts,
            "bundled": [
                {"path": rel, "sha256": sha256(appdir / rel),
                 "bytes": (appdir / rel).stat().st_size}
                for rel in sorted(packages[package]["bundled"])
            ],
        })
    for entry in entries:
        stems = set()
        for item in entry["bundled"]:
            name = Path(item["path"]).name
            stems.add(name.split(".so")[0] if ".so" in name else name)
        entry["stems"] = sorted(stems)

    add_special_sections(entries, packages, appdir, out_licenses, written, place,
                         check_only)

    inventory = {
        "generator": "tools/build-package-notices.py",
        "built": {"host": run("uname", "-rms"), "artifactAppdir": appdir.name},
        "artifact": {
            "appdir": "target/release/bundle/appimage/babel.AppDir",
            "appimageSha256": sha256(REPO / "target/release/bundle/appimage/babel_0.0.1_amd64.AppImage")
            if (REPO / "target/release/bundle/appimage/babel_0.0.1_amd64.AppImage").exists() else None,
        },
        "noticeFile": "usr/lib/babel/THIRD-PARTY-NOTICES.md",
        "scope": "Every ELF binary, provider module and font in the AppDir is attributed "
                 "in entries or trees. Own movables (icons, .desktop) need no third-party "
                 "notice. Compiled Rust-crate and transitive npm texts remain M6-10 work "
                 "(limitations L2/L3); direct JS runtime texts are retained.",
        "limitations": [
            "L1: Arch binary packages that ship no licence file use the canonical SPDX "
            "text from the installed licenses package; the upstream COPYING was verified "
            "locally only for Enchant, Hunspell and libltdl.",
            "L2: Transitive Rust-crate licence texts compiled into usr/bin/babel-desktop "
            "are not yet retained; only the statically linked libgit2 and the git2 binding "
            "licences are (M6-10 remainder).",
            "L3: Transitive npm module texts bundled into the frontend are not yet "
            "retained; direct runtime dependencies are (M6-10 remainder).",
        ],
        "entries": entries,
    }
    inv_text = json.dumps(inventory, indent=2) + "\n"

    if check_only:
        old = json.loads((DOCS / "package-inventory.json").read_text())
        old_native = sorted(b["path"] for e in old["entries"] if e["kind"] == "native"
                            for b in e["bundled"])
        new_native = sorted(b["path"] for e in entries if e["kind"] == "native"
                            for b in e["bundled"])
        if old_native != new_native:
            missing = [f for f in new_native if f not in old_native]
            extra = [f for f in old_native if f not in new_native]
            raise SystemExit(f"Notice inventory drift:\nmissing: {missing}\nextra: {extra}")
        print("notice inventory covers the artifact (texts/versions may differ by host)")
        return 0

    (DOCS / "package-inventory.json").write_text(inv_text)
    render_libraries_md(inventory)
    render_notices_md(inventory, out_licenses)
    print(f"wrote {len(entries)} entries, {len(list(out_licenses.iterdir()))} texts")
    return 0


if __name__ == "__main__":
    sys.exit(main())
